
[tox]
requires =
    tox-conda
    setuptools

[testenv]
whitelist_externals = git
setenv =
    PYTHONPATH = {toxinidir}
passenv = *
deps =
    pytest-html
    pytest-cov
commands =
    conda install orekit
    pytest --html=test_report/report.html
    pytest --cov-report html:test_report/cov_report --cov=datapro
